import {
  Column,
  Heading,
  Hr,
  Link,
  Row,
  Section,
  Text,
} from '@react-email/components';
import * as React from 'react';
import type { EnrichedItem } from '../types';
import { resolveThemeWithOverrides } from './themes';
import { resolveLayout } from './layouts';
import { buildLibrarySections, resolveBlocks, resolveItemDisplay } from '../appearance/resolve';
import type { Appearance } from '../appearance/schema';
import type { BlockId } from '../appearance/schema';
import { EmailShell } from './shell';

export interface DigestLink {
  url: string;
  label: string;
}

export interface DigestEmailProps {
  items: EnrichedItem[];
  unsubscribeUrl: string;
  appName: string;
  windowStart: Date;
  windowEnd: Date;
  intro?: string;
  disclaimer?: boolean;
  themeId?: string;
  layoutId?: string;
  requestLink?: DigestLink;
  personalLink?: DigestLink;
  freeformHtml?: string;
  appearance?: Appearance;
}

export function formatDateRange(start: Date, end: Date): string {
  const fmt = (d: Date, opts: Intl.DateTimeFormatOptions) =>
    new Intl.DateTimeFormat('en-US', opts).format(d);
  const sameYear = start.getFullYear() === end.getFullYear();
  const sameMonth = sameYear && start.getMonth() === end.getMonth();
  if (sameMonth) {
    return `${fmt(start, { month: 'long', day: 'numeric' })}–${fmt(end, { day: 'numeric' })}, ${end.getFullYear()}`;
  }
  if (sameYear) {
    return `${fmt(start, { month: 'short', day: 'numeric' })} – ${fmt(end, { month: 'short', day: 'numeric', year: 'numeric' })}`;
  }
  return `${fmt(start, { month: 'short', day: 'numeric', year: 'numeric' })} – ${fmt(end, { month: 'short', day: 'numeric', year: 'numeric' })}`;
}

export function DigestEmail({
  items,
  unsubscribeUrl,
  appName,
  windowStart,
  windowEnd,
  intro,
  disclaimer,
  themeId,
  layoutId,
  requestLink,
  personalLink,
  freeformHtml,
  appearance,
}: DigestEmailProps) {
  const theme = resolveThemeWithOverrides(themeId, appearance?.theme_overrides);
  const itemDisplay = resolveItemDisplay(appearance?.item_display);
  const header = appearance?.header;
  const footer = appearance?.footer;
  const sections = buildLibrarySections(items, appearance?.libraries);
  const { palette, fonts, layout } = theme;

  const dateRange = formatDateRange(windowStart, windowEnd);
  const itemNoun = items.length === 1 ? 'addition' : 'additions';

  const showDateRange = header?.show_date_range !== false;
  const showCount = header?.show_count !== false;
  const headerMetaParts: string[] = [];
  if (showDateRange) headerMetaParts.push(dateRange);
  if (showCount) headerMetaParts.push(`${items.length} ${itemNoun}`);

  const headerNode = (
    <Section>
      <Text
        style={{
          margin: 0,
          fontSize: 11,
          letterSpacing: layout.eyebrowLetterSpacing,
          textTransform: 'uppercase',
          color: palette.accent,
          fontWeight: 600,
        }}
      >
        {header?.eyebrow ?? `${appName} · Weekly`}
      </Text>
      <Heading
        as="h1"
        style={{
          margin: '10px 0 0',
          fontFamily: fonts.heading,
          fontSize: 36,
          lineHeight: 1.1,
          letterSpacing: layout.headingLetterSpacing,
          color: palette.ink,
          fontWeight: layout.headingWeight,
        }}
      >
        {header?.title ?? `New on ${appName}`}
      </Heading>
      {headerMetaParts.length > 0 ? (
        <Text
          style={{
            margin: '8px 0 0',
            fontSize: 14,
            color: palette.muted,
          }}
        >
          {headerMetaParts.join(' · ')}
        </Text>
      ) : null}
    </Section>
  );

  const introNode = intro ? (
    <Section style={{ marginTop: 20 }}>
      <Text
        style={{
          margin: 0,
          fontFamily: fonts.heading,
          fontSize: 17,
          lineHeight: 1.55,
          color: palette.ink,
          fontStyle: layout.introItalic ? 'italic' : 'normal',
        }}
      >
        {intro}
      </Text>
      {disclaimer ? (
        <Text
          style={{
            margin: '8px 0 0',
            fontFamily: fonts.body,
            fontSize: 12,
            letterSpacing: '0.04em',
            textTransform: 'uppercase',
            color: palette.muted,
          }}
        >
          Generated by AI
        </Text>
      ) : null}
    </Section>
  ) : null;

  const librariesNode =
    sections.length > 0 ? (
      <>
        <Hr
          style={{
            borderColor: palette.rule,
            borderStyle: 'solid',
            borderWidth: `0 0 ${layout.ruleWidth}px`,
            margin: '28px 0 0',
          }}
        />

        {sections.map(section => {
          const SectionLayout = resolveLayout(section.layoutId ?? layoutId);
          return (
            <Section key={section.name} style={{ marginTop: 32 }}>
              <Row>
                <Column>
                  <Text
                    style={{
                      margin: 0,
                      fontSize: 10,
                      letterSpacing: 3,
                      textTransform: 'uppercase',
                      color: palette.muted,
                      fontWeight: 600,
                    }}
                  >
                    {section.title}
                  </Text>
                </Column>
                <Column align="right">
                  <Text style={{ margin: 0, fontSize: 11, color: palette.muted }}>
                    {section.items.length} {section.items.length === 1 ? 'title' : 'titles'}
                  </Text>
                </Column>
              </Row>
              <Hr
                style={{
                  borderColor: palette.hairline,
                  borderStyle: 'solid',
                  borderWidth: '0 0 1px',
                  margin: '8px 0 0',
                }}
              />

              <SectionLayout.Items items={section.items} theme={theme} itemDisplay={itemDisplay} />
            </Section>
          );
        })}
      </>
    ) : null;

  const freeformNode = freeformHtml ? (
    <Section
      style={{
        marginTop: 40,
        background: palette.cardBg,
        border: `${layout.cardBorderWidth}px solid ${palette.hairline}`,
        borderRadius: layout.radius,
        boxShadow: layout.cardShadow,
        padding: 16,
      }}
    >
      <Row>
        <Column>
          <div
            style={{ fontSize: 14, lineHeight: 1.55, color: palette.ink }}
            dangerouslySetInnerHTML={{ __html: freeformHtml }}
          />
        </Column>
      </Row>
    </Section>
  ) : null;

  const actionsNode =
    requestLink || personalLink ? (
      <Section style={{ marginTop: 32, textAlign: 'center' }}>
        {requestLink ? (
          <Link
            href={requestLink.url}
            style={{
              display: 'inline-block',
              margin: '0 8px',
              padding: '10px 18px',
              borderRadius: layout.radius === 0 ? 0 : 999,
              background: palette.accent,
              color: palette.onAccent,
              fontSize: 13,
              fontWeight: 600,
              textDecoration: 'none',
              letterSpacing: 0.2,
            }}
          >
            {requestLink.label}
          </Link>
        ) : null}
        {personalLink ? (
          <Link
            href={personalLink.url}
            style={{
              display: 'inline-block',
              margin: '0 8px',
              fontSize: 13,
              fontWeight: 600,
              color: palette.accent,
              textDecoration: 'none',
            }}
          >
            {personalLink.label}
          </Link>
        ) : null}
      </Section>
    ) : null;

  const footerNode = (
    <>
      <Hr
        style={{
          borderColor: palette.rule,
          borderStyle: 'solid',
          borderWidth: `0 0 ${layout.ruleWidth}px`,
          margin: '48px 0 20px',
        }}
      />
      {footer?.show_app_label !== false ? (
        <Text
          style={{
            margin: 0,
            fontSize: 11,
            color: palette.muted,
            letterSpacing: 1,
            textTransform: 'uppercase',
            textAlign: 'center',
            fontWeight: 600,
          }}
        >
          {appName}
        </Text>
      ) : null}
      {footer?.text ? (
        <Text
          style={{
            margin: '6px 0 0',
            fontSize: 12,
            color: palette.muted,
            textAlign: 'center',
            lineHeight: 1.5,
          }}
        >
          {footer.text}
        </Text>
      ) : null}
    </>
  );

  const blockNodes: Record<BlockId, React.ReactNode> = {
    header: headerNode,
    intro: introNode,
    libraries: librariesNode,
    freeform: freeformNode,
    actions: actionsNode,
    footer: footerNode,
  };
  const ordered = resolveBlocks(appearance?.blocks);

  return (
    <EmailShell
      theme={theme}
      appName={appName}
      unsubscribeUrl={unsubscribeUrl}
      previewText={`${items.length} new on ${appName} · ${dateRange}`}
    >
      {ordered
        .filter(b => b.enabled)
        .map(b => (
          <React.Fragment key={b.id}>{blockNodes[b.id]}</React.Fragment>
        ))}
    </EmailShell>
  );
}
