import { describe, it, expect } from 'vitest';
import { render } from '@react-email/render';
import { createElement } from 'react';
import { DigestEmail, formatDateRange } from './digest';
import type { EnrichedItem } from '../types';

const items: EnrichedItem[] = [{
  guid: 'g1', title: 'A Movie', mediaType: 'movie', libraryName: 'Movies',
  addedAt: new Date('2026-05-01T00:00:00Z'), rating: 7.4,
  posterUrl: 'https://image.tmdb.org/t/p/w500/p.jpg', overview: 'A summary',
}];

describe('formatDateRange', () => {
  it('formats a same-month range as "Month D–D, YYYY"', () => {
    expect(formatDateRange(new Date(2026, 4, 14), new Date(2026, 4, 21))).toBe('May 14–21, 2026');
  });

  it('formats a cross-month, same-year range', () => {
    expect(formatDateRange(new Date(2026, 4, 28), new Date(2026, 5, 3))).toBe('May 28 – Jun 3, 2026');
  });
});

describe('DigestEmail', () => {
  const baseProps = {
    items,
    unsubscribeUrl: 'https://x/u',
    appName: 'Tortuga',
    windowStart: new Date('2026-05-01T00:00:00Z'),
    windowEnd: new Date('2026-05-08T00:00:00Z'),
  };

  it('renders subject + sections', async () => {
    const html = await render(DigestEmail(baseProps));
    expect(html).toContain('A Movie');
    expect(html).toContain('Movies');
    expect(html).toContain('Unsubscribe');
  });

  it('renders a "Manage preferences" link next to Unsubscribe when preferencesUrl is set', async () => {
    const html = await render(DigestEmail({ ...baseProps, preferencesUrl: 'https://x/preferences?token=abc' }));
    expect(html).toContain('Manage preferences');
    expect(html).toContain('https://x/preferences?token=abc');
  });

  it('renders Open in Plex when plexUrl present', async () => {
    const html = await render(
      DigestEmail({
        ...baseProps,
        items: [
          { ...items[0], plexUrl: 'https://app.plex.tv/desktop/#!/server/abc/details?key=x' },
        ],
      }),
    );
    expect(html).toContain('Open in Plex');
    expect(html).toContain('https://app.plex.tv/desktop/');
  });

  it('omits Open in Plex when plexUrl missing', async () => {
    const html = await render(DigestEmail(baseProps));
    expect(html).not.toContain('Open in Plex');
  });

  it('renders intro, links, and freeform when present', async () => {
    const html = await render(
      DigestEmail({
        ...baseProps,
        intro: 'A curated week of cinema.',
        requestLink: { url: 'https://req.example', label: 'Make a request' },
        personalLink: { url: 'https://example.com', label: 'example.com' },
        freeformHtml: '<p>Maintenance Sunday.</p>',
      }),
    );
    expect(html).toContain('A curated week of cinema.');
    expect(html).toContain('https://req.example');
    expect(html).toContain('Make a request');
    expect(html).toContain('https://example.com');
    expect(html).toContain('Maintenance Sunday.');
  });

  it('renders the AI disclaimer under the intro when enabled', async () => {
    const html = await render(
      DigestEmail({ ...baseProps, intro: 'A curated week.', disclaimer: true }),
    );
    expect(html).toContain('Generated by AI');
  });

  it('omits the disclaimer when disabled', async () => {
    const html = await render(
      DigestEmail({ ...baseProps, intro: 'A curated week.', disclaimer: false }),
    );
    expect(html).not.toContain('Generated by AI');
  });

  it('omits the disclaimer when there is no intro even if enabled', async () => {
    const html = await render(DigestEmail({ ...baseProps, disclaimer: true }));
    expect(html).not.toContain('Generated by AI');
  });

  it('applies the requested theme palette', async () => {
    const html = await render(DigestEmail({ ...baseProps, themeId: 'dark-luxury' }));
    expect(html).toContain('#0e0d0b'); // dark-luxury paper
    expect(html).toContain('#c9a24b'); // dark-luxury accent
  });

  it('falls back to the editorial theme for an unknown theme id', async () => {
    const html = await render(DigestEmail({ ...baseProps, themeId: 'nope' }));
    expect(html).toContain('#faf8f4'); // editorial paper
    expect(html).not.toContain('#0e0d0b');
  });

  it('omits intro/links/freeform when absent', async () => {
    const html = await render(DigestEmail(baseProps));
    expect(html).not.toContain('Make a request');
    expect(html).not.toContain('Maintenance Sunday.');
    expect(html).not.toContain('A curated week of cinema.');
    expect(html).not.toContain('example.com');
  });

  it('defaults to the List layout (88px poster)', async () => {
    const html = await render(DigestEmail(baseProps));
    expect(html).toContain('width="88"');
    expect(html).not.toContain('width="150"');
    expect(html).not.toContain('width="584"');
  });

  it('renders the Gallery layout (150px posters, no 88px card poster)', async () => {
    const html = await render(DigestEmail({ ...baseProps, layoutId: 'gallery' }));
    expect(html).toContain('width="150"');
    expect(html).not.toContain('width="88"');
  });

  it('renders the Magazine layout (full-width 584px poster)', async () => {
    const html = await render(DigestEmail({ ...baseProps, layoutId: 'magazine' }));
    expect(html).toContain('width="584"');
  });

  it('renders the Compact layout with no posters', async () => {
    const html = await render(DigestEmail({ ...baseProps, layoutId: 'compact' }));
    expect(html).not.toContain('image.tmdb.org');
    expect(html).toContain('A Movie');
  });

  it('falls back to List for an unknown layout id', async () => {
    const html = await render(DigestEmail({ ...baseProps, layoutId: 'bogus' }));
    expect(html).toContain('width="88"');
    expect(html).not.toContain('width="150"');
    expect(html).not.toContain('width="584"');
  });
});

describe('DigestEmail leaving block', () => {
  const baseProps = {
    items,
    unsubscribeUrl: 'https://x/u',
    appName: 'Tortuga',
    windowStart: new Date('2026-05-01T00:00:00Z'),
    windowEnd: new Date('2026-05-08T00:00:00Z'),
  };

  const leavingItem: EnrichedItem = {
    guid: 'leave-1',
    title: 'The Departing Film',
    mediaType: 'movie',
    libraryName: 'Movies',
    addedAt: new Date('2026-04-01T00:00:00Z'),
    rating: 8.1,
    posterUrl: 'https://image.tmdb.org/t/p/w500/x.jpg',
    overview: 'A summary',
    leavesAt: new Date('2026-09-06T12:00:00Z'),
  };

  for (const layoutId of ['list', 'gallery', 'magazine', 'compact', 'timeline']) {
    it(`renders the leaving heading and exactly one Leaves label per item in the ${layoutId} layout`, async () => {
      const html = await render(
        DigestEmail({
          ...baseProps,
          layoutId,
          leavingItems: [leavingItem],
          leavingHeading: 'On its way out',
          timezone: 'UTC',
        }),
      );
      expect(html).toContain('On its way out');
      expect(html).toContain('The Departing Film');
      expect(html).toContain('Leaves');
      expect(html).toContain('Sep 6');
      expect(html.match(/Leaves /g)?.length).toBe(1);
    });
  }

  it('formats the Leaves date in the given timezone', async () => {
    const html = await render(
      DigestEmail({
        ...baseProps,
        leavingItems: [leavingItem],
        timezone: 'America/Los_Angeles', // 12:00 UTC -> Sep 6 05:00 PDT, still Sep 6
      }),
    );
    expect(html).toContain('Leaves Sun, Sep 6');
  });

  it('omits the leaving section entirely when the list is empty', async () => {
    const html = await render(
      DigestEmail({ ...baseProps, leavingItems: [], leavingHeading: 'On its way out' }),
    );
    expect(html).not.toContain('On its way out');
  });

  it('omits the leaving section when leavingItems is absent', async () => {
    const html = await render(DigestEmail({ ...baseProps, leavingHeading: 'On its way out' }));
    expect(html).not.toContain('On its way out');
  });

  it('hides the leaving block when disabled via appearance, even with items', async () => {
    const html = await render(
      DigestEmail({
        ...baseProps,
        leavingItems: [leavingItem],
        leavingHeading: 'On its way out',
        appearance: { blocks: [{ id: 'leaving', enabled: false }] },
      }),
    );
    expect(html).not.toContain('On its way out');
  });

  it('defaults to enabled, positioned after the library sections and before freeform/footer', async () => {
    const html = await render(
      DigestEmail({
        ...baseProps,
        leavingItems: [leavingItem],
        leavingHeading: 'On its way out',
        freeformHtml: '<p>Note.</p>',
      }),
    );
    const librariesIdx = html.indexOf('Movies');
    const leavingIdx = html.indexOf('On its way out');
    const freeformIdx = html.indexOf('Note.');
    expect(librariesIdx).toBeGreaterThan(-1);
    expect(leavingIdx).toBeGreaterThan(librariesIdx);
    expect(freeformIdx).toBeGreaterThan(leavingIdx);
  });
});

describe('DigestEmail appearance', () => {
  const items: EnrichedItem[] = [
    { guid: 'a', libraryName: 'Movies', title: 'Alpha', mediaType: 'movie', addedAt: new Date('2026-05-20T00:00:00Z'), overview: 'x', rating: 0, posterUrl: '' },
    { guid: 'b', libraryName: 'TV', title: 'Beta', mediaType: 'show', addedAt: new Date('2026-05-21T00:00:00Z'), overview: 'y', rating: 0, posterUrl: '' },
  ];

  const base = { items, unsubscribeUrl: 'http://u/x', appName: 'Plex', windowStart: new Date('2026-05-20'), windowEnd: new Date('2026-05-27') };

  it('renders identically when appearance is undefined (parity)', async () => {
    const a = await render(createElement(DigestEmail, base));
    const b = await render(createElement(DigestEmail, { ...base, appearance: {} }));
    expect(a).toBe(b);
  });

  it('hides a block when disabled', async () => {
    const html = await render(createElement(DigestEmail, {
      ...base,
      appearance: { blocks: [{ id: 'footer', enabled: false }] },
    }));
    expect(html).toContain('Unsubscribe'); // unsubscribe is never removable
    // The standalone app-label paragraph (rendered as `>Plex</p>`) is gone.
    // Note: the unsubscribe line still names the app ("access to Plex."), so we
    // target the label paragraph's exact `>Plex</p>` marker rather than `>Plex<`,
    // which also appears in the unsubscribe sentence.
    expect(html).not.toContain('>Plex</p>'); // app-label text removed
  });

  it('applies a custom header title and hides the count', async () => {
    const html = await render(createElement(DigestEmail, {
      ...base,
      appearance: { header: { title: 'Fresh Picks', show_count: false, show_date_range: true } },
    }));
    expect(html).toContain('Fresh Picks');
  });

  it('reorders and renames library sections', async () => {
    const html = await render(createElement(DigestEmail, {
      ...base,
      appearance: { libraries: [{ name: 'TV', enabled: true, title: 'Shows' }, { name: 'Movies', enabled: true }] },
    }));
    expect(html.indexOf('Shows')).toBeLessThan(html.indexOf('Movies'));
  });
});

describe('DigestEmail limits + issue URL', () => {
  const manyMovies: EnrichedItem[] = Array.from({ length: 5 }, (_, i) => ({
    guid: `m${i}`, libraryName: 'Movies', title: `Movie ${i}`, mediaType: 'movie',
    addedAt: new Date('2026-05-20T00:00:00Z'), overview: 'x', rating: 0, posterUrl: '',
  }));
  const leavingItems: EnrichedItem[] = Array.from({ length: 4 }, (_, i) => ({
    guid: `l${i}`, libraryName: 'Movies', title: `Leaving ${i}`, mediaType: 'movie',
    addedAt: new Date('2026-05-20T00:00:00Z'), overview: 'x', rating: 0, posterUrl: '',
    leavesAt: new Date('2026-09-06T12:00:00Z'),
  }));

  const base = {
    items: manyMovies,
    unsubscribeUrl: 'http://u/x',
    appName: 'Plex',
    windowStart: new Date('2026-05-20'),
    windowEnd: new Date('2026-05-27'),
  };

  it('truncates a library section at the limit and adds a "View all N" link', async () => {
    const html = await render(createElement(DigestEmail, {
      ...base,
      limits: { perLibrarySection: 2 },
      issueUrl: 'https://x/issues/abc',
    }));
    expect(html).toContain('Movie 0');
    expect(html).toContain('Movie 1');
    expect(html).not.toContain('Movie 2');
    expect(html).toMatch(/View all\s*(<!-- -->)?5/);
    expect(html).toContain('https://x/issues/abc#movies');
  });

  it('omits the "View all" link when the section is under the limit', async () => {
    const html = await render(createElement(DigestEmail, {
      ...base,
      limits: { perLibrarySection: 10 },
      issueUrl: 'https://x/issues/abc',
    }));
    expect(html).not.toContain('View all');
  });

  it('caps the leaving-soon section only when leavingSoon is set', async () => {
    const uncapped = await render(createElement(DigestEmail, {
      ...base,
      leavingItems,
      limits: { perLibrarySection: 99 },
      issueUrl: 'https://x/issues/abc',
    }));
    expect(uncapped).toContain('Leaving 3');
    expect(uncapped).not.toContain('View all');

    const capped = await render(createElement(DigestEmail, {
      ...base,
      leavingItems,
      limits: { perLibrarySection: 99, leavingSoon: 2 },
      issueUrl: 'https://x/issues/abc',
    }));
    expect(capped).toContain('Leaving 0');
    expect(capped).toContain('Leaving 1');
    expect(capped).not.toContain('Leaving 2');
    expect(capped).toMatch(/View all\s*(<!-- -->)?4/);
    expect(capped).toContain('https://x/issues/abc#leaving-soon');
  });

  it('renders a "View this issue online" link above the intro when issueUrl is set', async () => {
    const html = await render(createElement(DigestEmail, {
      ...base,
      intro: 'Hello.',
      issueUrl: 'https://x/issues/abc',
    }));
    expect(html).toContain('View this issue online');
    const onlineIdx = html.indexOf('View this issue online');
    const introIdx = html.indexOf('Hello.');
    expect(onlineIdx).toBeGreaterThan(-1);
    expect(onlineIdx).toBeLessThan(introIdx);
  });

  it('omits the "View this issue online" link when issueUrl is unset', async () => {
    const html = await render(createElement(DigestEmail, base));
    expect(html).not.toContain('View this issue online');
  });

  it('web variant (no limits, no unsubscribeUrl) renders every item and no unsubscribe line', async () => {
    const html = await render(createElement(DigestEmail, {
      ...base,
      unsubscribeUrl: undefined,
      leavingItems,
    }));
    expect(html).toContain('Movie 0');
    expect(html).toContain('Movie 4');
    expect(html).toContain('Leaving 3');
    expect(html).not.toContain('Unsubscribe');
    expect(html).not.toContain('View all');
  });

  it('renders stable section id anchors for library and leaving sections', async () => {
    const html = await render(createElement(DigestEmail, { ...base, leavingItems }));
    expect(html).toContain('id="movies"');
    expect(html).toContain('id="leaving-soon"');
  });

  it('email variant applies a library rule max_items cap but reports the true uncapped total', async () => {
    const html = await render(createElement(DigestEmail, {
      ...base,
      limits: { perLibrarySection: 99 }, // render cap is generous; the rule cap should still bite
      appearance: { libraries: [{ name: 'Movies', enabled: true, max_items: 2 }] },
      issueUrl: 'https://x/issues/abc',
    }));
    expect(html).toContain('Movie 0');
    expect(html).toContain('Movie 1');
    expect(html).not.toContain('Movie 2');
    expect(html).toMatch(/View all\s*(<!-- -->)?5/); // true total, not the capped count
  });

  it('web variant ignores a library rule max_items cap and renders every item', async () => {
    const html = await render(createElement(DigestEmail, {
      ...base,
      unsubscribeUrl: undefined,
      appearance: { libraries: [{ name: 'Movies', enabled: true, max_items: 2 }] },
    }));
    expect(html).toContain('Movie 0');
    expect(html).toContain('Movie 4');
    expect(html).not.toContain('View all');
  });
});
