import {
  Body,
  Column,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Row,
  Section,
  Text,
} from '@react-email/components';
import * as React from 'react';
import type { EnrichedItem } from '../types';
import { resolveTheme } from './themes';
import { resolveLayout } from './layouts';

export interface DigestLink {
  url: string;
  label: string;
}

export interface DigestEmailProps {
  items: EnrichedItem[];
  unsubscribeUrl: string;
  appName: string;
  windowStart: Date;
  windowEnd: Date;
  intro?: string;
  disclaimer?: boolean;
  themeId?: string;
  layoutId?: string;
  requestLink?: DigestLink;
  personalLink?: DigestLink;
  freeformHtml?: string;
}

export function formatDateRange(start: Date, end: Date): string {
  const fmt = (d: Date, opts: Intl.DateTimeFormatOptions) =>
    new Intl.DateTimeFormat('en-US', opts).format(d);
  const sameYear = start.getFullYear() === end.getFullYear();
  const sameMonth = sameYear && start.getMonth() === end.getMonth();
  if (sameMonth) {
    return `${fmt(start, { month: 'long', day: 'numeric' })}–${fmt(end, { day: 'numeric' })}, ${end.getFullYear()}`;
  }
  if (sameYear) {
    return `${fmt(start, { month: 'short', day: 'numeric' })} – ${fmt(end, { month: 'short', day: 'numeric', year: 'numeric' })}`;
  }
  return `${fmt(start, { month: 'short', day: 'numeric', year: 'numeric' })} – ${fmt(end, { month: 'short', day: 'numeric', year: 'numeric' })}`;
}


export function DigestEmail({
  items,
  unsubscribeUrl,
  appName,
  windowStart,
  windowEnd,
  intro,
  disclaimer,
  themeId,
  layoutId,
  requestLink,
  personalLink,
  freeformHtml,
}: DigestEmailProps) {
  const theme = resolveTheme(themeId);
  const activeLayout = resolveLayout(layoutId);
  const { palette, fonts, layout } = theme;

  const sections = new Map<string, EnrichedItem[]>();
  for (const it of items) {
    const list = sections.get(it.libraryName) ?? [];
    list.push(it);
    sections.set(it.libraryName, list);
  }
  const dateRange = formatDateRange(windowStart, windowEnd);
  const itemNoun = items.length === 1 ? 'addition' : 'additions';

  return (
    <Html>
      <Head>
        <meta name="color-scheme" content={theme.colorScheme} />
        <meta name="supported-color-schemes" content={theme.colorScheme} />
      </Head>
      <Preview>{`${items.length} new on ${appName} · ${dateRange}`}</Preview>
      <Body
        style={{
          margin: 0,
          padding: 0,
          background: palette.paper,
          color: palette.ink,
          fontFamily: fonts.body,
          WebkitFontSmoothing: 'antialiased',
        }}
      >
        <Container
          style={{
            maxWidth: 640,
            margin: '0 auto',
            padding: '40px 28px 56px',
            background: palette.paper,
          }}
        >
          <Section>
            <Text
              style={{
                margin: 0,
                fontSize: 11,
                letterSpacing: layout.eyebrowLetterSpacing,
                textTransform: 'uppercase',
                color: palette.accent,
                fontWeight: 600,
              }}
            >
              {appName} · Weekly
            </Text>
            <Heading
              as="h1"
              style={{
                margin: '10px 0 0',
                fontFamily: fonts.heading,
                fontSize: 36,
                lineHeight: 1.1,
                letterSpacing: layout.headingLetterSpacing,
                color: palette.ink,
                fontWeight: layout.headingWeight,
              }}
            >
              New on {appName}
            </Heading>
            <Text
              style={{
                margin: '8px 0 0',
                fontSize: 14,
                color: palette.muted,
              }}
            >
              {dateRange} · {items.length} {itemNoun}
            </Text>
          </Section>

          {intro ? (
            <Section style={{ marginTop: 20 }}>
              <Text
                style={{
                  margin: 0,
                  fontFamily: fonts.heading,
                  fontSize: 17,
                  lineHeight: 1.55,
                  color: palette.ink,
                  fontStyle: layout.introItalic ? 'italic' : 'normal',
                }}
              >
                {intro}
              </Text>
              {disclaimer ? (
                <Text
                  style={{
                    margin: '8px 0 0',
                    fontFamily: fonts.body,
                    fontSize: 12,
                    letterSpacing: '0.04em',
                    textTransform: 'uppercase',
                    color: palette.muted,
                  }}
                >
                  Generated by AI
                </Text>
              ) : null}
            </Section>
          ) : null}

          <Hr
            style={{
              borderColor: palette.rule,
              borderStyle: 'solid',
              borderWidth: `0 0 ${layout.ruleWidth}px`,
              margin: '28px 0 0',
            }}
          />

          {Array.from(sections.entries()).map(([library, group]) => (
            <Section key={library} style={{ marginTop: 32 }}>
              <Row>
                <Column>
                  <Text
                    style={{
                      margin: 0,
                      fontSize: 10,
                      letterSpacing: 3,
                      textTransform: 'uppercase',
                      color: palette.muted,
                      fontWeight: 600,
                    }}
                  >
                    {library}
                  </Text>
                </Column>
                <Column align="right">
                  <Text style={{ margin: 0, fontSize: 11, color: palette.muted }}>
                    {group.length} {group.length === 1 ? 'title' : 'titles'}
                  </Text>
                </Column>
              </Row>
              <Hr
                style={{
                  borderColor: palette.hairline,
                  borderStyle: 'solid',
                  borderWidth: '0 0 1px',
                  margin: '8px 0 0',
                }}
              />

              <activeLayout.Items items={group} theme={theme} />
            </Section>
          ))}

          {freeformHtml ? (
            <Section
              style={{
                marginTop: 40,
                background: palette.cardBg,
                border: `${layout.cardBorderWidth}px solid ${palette.hairline}`,
                borderRadius: layout.radius,
                boxShadow: layout.cardShadow,
                padding: 16,
              }}
            >
              <Row>
                <Column>
                  <div
                    style={{ fontSize: 14, lineHeight: 1.55, color: palette.ink }}
                    dangerouslySetInnerHTML={{ __html: freeformHtml }}
                  />
                </Column>
              </Row>
            </Section>
          ) : null}

          {requestLink || personalLink ? (
            <Section style={{ marginTop: 32, textAlign: 'center' }}>
              {requestLink ? (
                <Link
                  href={requestLink.url}
                  style={{
                    display: 'inline-block',
                    margin: '0 8px',
                    padding: '10px 18px',
                    borderRadius: layout.radius === 0 ? 0 : 999,
                    background: palette.accent,
                    color: palette.onAccent,
                    fontSize: 13,
                    fontWeight: 600,
                    textDecoration: 'none',
                    letterSpacing: 0.2,
                  }}
                >
                  {requestLink.label}
                </Link>
              ) : null}
              {personalLink ? (
                <Link
                  href={personalLink.url}
                  style={{
                    display: 'inline-block',
                    margin: '0 8px',
                    fontSize: 13,
                    fontWeight: 600,
                    color: palette.accent,
                    textDecoration: 'none',
                  }}
                >
                  {personalLink.label}
                </Link>
              ) : null}
            </Section>
          ) : null}

          <Hr
            style={{
              borderColor: palette.rule,
              borderStyle: 'solid',
              borderWidth: `0 0 ${layout.ruleWidth}px`,
              margin: '48px 0 20px',
            }}
          />
          <Text
            style={{
              margin: 0,
              fontSize: 11,
              color: palette.muted,
              letterSpacing: 1,
              textTransform: 'uppercase',
              textAlign: 'center',
              fontWeight: 600,
            }}
          >
            {appName}
          </Text>
          <Text
            style={{
              margin: '6px 0 0',
              fontSize: 12,
              color: palette.muted,
              textAlign: 'center',
              lineHeight: 1.5,
            }}
          >
            You&apos;re receiving this because you have access to {appName}.
            <br />
            <Link
              href={unsubscribeUrl}
              style={{ color: palette.muted, textDecoration: 'underline' }}
            >
              Unsubscribe
            </Link>
          </Text>
        </Container>
      </Body>
    </Html>
  );
}

